force-app/main/default/objects/Item__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>B</fullName>
                <isActive>false</isActive>
                <label>B</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>D</fullName>
                <isActive>false</isActive>
                <label>D</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemPurchaseController.cls
public with sharing class ItemPurchaseController {

    @AuraEnabled(cacheable=true)
    public static Account getAccount(Id accountId) {

        if (accountId == null) {
            return null;
        }

        return [
            SELECT Id,
                   Name,
                   AccountNumber,
                   Industry
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Item__c> getItems(
        String family,
        String type,
        String searchKey
    ) {

        String query =
            'SELECT Id, Name, Price__c, Image__c, Family__c, Type__c, Description__c ' +
            'FROM Item__c WHERE Id != null ';

        if (family != null && family != '') {
            query += ' AND Family__c = :family';
        }

        if (type != null && type != '') {
            query += ' AND Type__c = :type';
        }

        if (searchKey != null && searchKey != '') {

            String search = '%' + searchKey + '%';

            query +=
                ' AND (Name LIKE :search OR Description__c LIKE :search)';
        }

        query += ' ORDER BY Name LIMIT 100';

        return Database.query(query);
    }
    

     
    @AuraEnabled(cacheable=true)
    public static List<String> getTypePicklistValues() {
        Schema.DescribeFieldResult fieldResult = Item__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<String> values = new List<String>();
        for(Schema.PicklistEntry f : ple){
            values.add(f.getValue());
        }
        return values;
    }

    
    @AuraEnabled(cacheable=true)
    public static List<String> getFamilyPicklistValues() {
        Schema.DescribeFieldResult fieldResult = Item__c.Family__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<String> values = new List<String>();
        for(Schema.PicklistEntry f : ple){
            values.add(f.getValue());
        }
        return values;
    }

    @AuraEnabled
    public static Item__c createItem(String name, String description, String family, String type, Decimal price) {
        String imageUrl = UnsplashService.getImageUrl(name);

        Item__c newItem = new Item__c(
            Name = name,
            Description__c = description,
            Family__c = family,
            Type__c = type,
            Price__c = price,
            Image__c = imageUrl
        );
        insert newItem;
        return newItem;
    }
}